### PR TITLE
added combination/permutation/etc length

### PR DESCRIPTION
**Pull request by sithmel**
Combinatory generator functions are now iterable objects. With a "length" property method.

I didn't figure out yet how to fix TS declaration, but I am sure it is broken (I tested it)

### CODE REVIEW

**Comment by KSXGitHub** [comment]
As long as `get length` is `O(1)`, I'm fine with it.

> I didn't figure out yet how to fix TS declaration, but I am sure it is broken (I tested it)

I may update it soon, but for the time being, use `<ExistingReturnType> & { readonly length: number }`

**Comment by sithmel** [comment]
I added the type declaration as advised

**Comment by KSXGitHub** [comment]
@sithmel Also, since it no longer produce an iterator, but instead, returns iterable instances of some classes, you should also change `IteratorIterable<...> & ...` to `Iterable<...> & ...`

**Comment by KSXGitHub** [comment]
Another thing, is classes necessary? Why don't you just use objects and scoped local functions in place of classes and methods? For example:

```javascript
// instead of
class Instance {
  constructor (value) { this.value = value }
  * [Symbol.iterator] () { yield * this.value }
  get length () { return value.length }
}

// use
const createInstance = value => ({
  * [Symbol.iterator] () { yield * value },
  get length () { return value.length }
})
```

**Comment by sithmel** [comment]
@KSXGitHub why do you think it is better avoiding using classes in this case ?

**Comment by KSXGitHub** [comment]
@sithmel Smaller size, less overhead.

**Comment by sithmel** [comment]
I am now using simple objects

**Pull request merged**
