### PR TITLE
added negative indecies to slice

### PR DESCRIPTION
**Pull request by sithmel**

### CODE REVIEW

**Comment by conartist6** [comment]
Looks good now.

**Comment by conartist6** [comment]
Oh, and be sure to run coverage before you commit. Might want to add that to a hook of some kind.

**Comment by sithmel** [comment]
I added a circular buffer implementation. I didn't find one I like on npm, so I wrote a simple one (only 14 LOC).
I think we can do better when "start" and "end" are both negative. I am having a look at it

**Comment by conartist6** [comment]
Might want to make your buffer iterable... I guess in that case you could if you made a buffer of end-start size.

**Pull request merged**
