### PR TITLE
Add interpose method

### PR DESCRIPTION
**Pull request by conartist6**
Name is taken from same method in Immutable.js.

### CODE REVIEW

**Comment by sithmel** [comment]
You can get that easily with:
```
flat(zip(iterable,repeat(null)))
```
Am I right ?

**Comment by conartist6** [comment]
Errr, aside from being three functions instead of one, I think the key difference would be that this only inserts the given item between, not before the first or after the last element.

**Comment by conartist6** [comment]
Yeah. Basically the use case is the same as `Array.prototype.join`, just that you end up with an array instead of a string. This is particularly useful when working with React, where you may have an array of React Elements and want to put some divider (like ", ") between each of them. I'll merge it.

**Comment by conartist6** [comment]
@sithmel could you do another beta release? I added this because I need it right away in sequins.

**Pull request merged**
