### PR TITLE
Alternate implementation of partition() function

### PR DESCRIPTION
**Pull request by KSXGitHub**
Differences from https://github.com/sithmel/iter-tools/pull/118:
  - Uses loop in place for recursion
  - Returns pair of iterators

### CODE REVIEW

**Comment by KSXGitHub** [comment]
I tried to change `while (true)` to `while (!exhausted)` to make the code looks nicer but it didn't pass the test. @sithmel, do you have any idea how to improve this?

**Comment by sithmel** [comment]
```while (!exhausted)``` is not correct because you have exhausted the input iterable, but you still need to flush the queue

**Comment by sithmel** [comment]
I like this implementation.

**Comment by sithmel** [comment]
Even better. Shall I close #118 ?

**Comment by KSXGitHub** [comment]
> Even better. Shall I close #118 ?

My TODO list is there!

**Comment by KSXGitHub** [comment]
> Even better. Shall I close #118 ?

Beside, if you merge this, GitHub will automatically close #118

**Pull request merged**
